### ISSUE TITLE
Py wheel fails to build with Python 3.12.0

### ISSUE THREAD

**Issue by yuanweixin** [duckdb/duckdb#9563]
### What happens?

duckdb python package 0.9.1 fails to build with python 3.12.0

When I downgrade to python 3.11.0 it builds successfully. 

In python 3.12.0,  `Legacy Unicode APIs based on Py_UNICODE* representation has been removed. Please migrate to APIs based on UTF-8 or wchar_t*.`. (https://docs.python.org/dev/whatsnew/3.12.html). 

Error message I get: 
```
      src/numpy/numpy_scan.cpp:402:69: error: ‘PyUnicode_WCHAR_KIND’ was not declared in this scope; did you mean ‘PyUnicode_4BYTE_KIND’?
                
```

### To Reproduce

I am using conda, so the repro here is assuming you use it to isolate your dependency. 

conda create -n repro python=3.12.0
conda activate repro 
pip install duckdb --upgrade --pre

...Downloading duckdb-0.9.2.dev242.tar.gz (10.7 MB)

### OS:

Linux devvm 6.2.0-36-generic #37~22.04.1-Ubuntu SMP PREEMPT_DYNAMIC Mon Oct  9 15:34:04 UTC 2 x86_64 x86_64 x86_64 GNU/Linux

### DuckDB Version:

0.9.1

### DuckDB Client:

python

### Full Name:

Wei Xin Yuan

### Affiliation:

None 

### Have you tried this on the latest `main` branch?

I have tested with a release build (and could not test with a main build)

### Have you tried the steps to reproduce? Do they include all relevant data and configuration? Does the issue you report still appear there?

- [X] Yes, I have

**Comment by Tishj** [comment]
#9208 

Thanks, we're aware :)

**Comment by Dornish** [comment]
> #9222
> 
> Thanks, we're aware :)

Hi @Tishj . I'm a git beginner so maybe I'm reading things wrong, please bear with me. This build 9222 you're linking was published on oct 5, no? Is it not yet fully released? When can we expect this patch to be applied so we can retry installing duckdb with 3.12?

**Comment by Mause** [comment]
> > #9222
> > 
> > Thanks, we're aware :)
> 
> Hi @Tishj . I'm a git beginner so maybe I'm reading things wrong, please bear with me. This build 9222 you're linking was published on oct 5, no? Is it not yet fully released? When can we expect this patch to be applied so we can retry installing duckdb with 3.12?

That pull request was closed without being merged, more work is required

**Comment by Dornish** [comment]
Thanks!

**Comment by Dornish** [comment]
> > > #9222
> > > Thanks, we're aware :)
> > 
> > 
> > Hi @Tishj . I'm a git beginner so maybe I'm reading things wrong, please bear with me. This build 9222 you're linking was published on oct 5, no? Is it not yet fully released? When can we expect this patch to be applied so we can retry installing duckdb with 3.12?
> 
> That pull request was closed without being merged, more work is required

Thank you for clarifying.

**Comment by Mause** [comment]
Sorry for the wait folks, Py3.12 turned out to be a tricky one
