### PR TITLE
Inline ListLambdaBindData methods

### PR DESCRIPTION
**Pull request by Maxxen**
Im not sure exactly why, but somehow the rust linux build broke at the linking step after upgrading to v1.2.0, complaining about missing typeinfo for the ListLambdaBindData. ... I think this is because the destructor/virtual methods are not present in the resulting unity build for planner/expression? 

Either way, moving them to the header seems to resolve it on my private fork. Here the compilation succeeds, although there are some test failures as I had to bump the tag to get the rust build script to work (you can't just give it a branch/commit) https://github.com/Maxxen/duckdb-rs/actions/runs/13346304316/job/37277138519

The annoying thing with the rust client is that it requires checking out a versioned tag of the duckdb source tree, so Im not sure how to get this patch applied over there, but we can figure that out separately. Otherwise it's going to be fixed when we bump to v1.2.1 in a couple weeks. 

Related issue https://github.com/duckdb/duckdb-rs/issues/436

### CODE REVIEW

**Comment by Mytherin** [comment]
Thanks for the PR!

I think what is going wrong here is that `lambda_functions.cpp` is in the core functions extension, but `lambda_functions.hpp` is in mainline DuckDB. This is the first release in which the core functions extension is separated.

The fix looks good to me - but the fact that this is failing indicates to me the Rust build is perhaps not including the core functions extension? If so, I would also consider enabling that - since that is enabled on essentially all builds (except for WASM).

**Comment by Mytherin** [comment]
Also if you want this to be in the next bug-fix release it should target `v1.2-histrionicus`

**Comment by Mytherin** [comment]
The `FunctionData` destructor move is likely not necessary either - `undefined reference to `typeinfo for XXX` generally means one of the methods on that class is not defined (which is likely the `Copy/Equals` methods).

**Comment by Mytherin** [comment]
Can you retarget this to v1.2.1 and remove the changes to `FunctionData`?

**Comment by Maxxen** [comment]
I was going to wait with this and see if including core_functions would solve the rust issue - do you still think these changes (except FunctionData stuff) are worthwhile regardless?

**Comment by Mytherin** [comment]
Yes, without moving the definition there's a discrepancy in where the header is located and where the source file is defined (i.e. the header lives in core, but the implementation lives in an extension). This basically always forces core functions to be statically loaded.

**Comment by Maxxen** [comment]
Can't figure out how to rebase without pulling in half of main, made a new PR here https://github.com/duckdb/duckdb/pull/16327
