### ISSUE TITLE
Build from source fails.

### ISSUE THREAD

**Issue by VivekJaganath** [duckdb/duckdb#4351]
### What happens?

I am trying to include the HTTPFS in the package and build duckdb from source. But the build fails while building CXX object extension. i have tried ubuntu and aws linux image, with python 3.7 to 3.10 and the issue persists across.

/duckdb/extension/httpfs/../../third_party/httplib/httplib.hpp:4189:46: warning: 'int SHA256_Init(SHA256_CTX*)' is deprecated: Since OpenSSL 3.0 [-Wdeprecated-declarations]
 4189 |         return message_digest<SHA256_CTX>(s, SHA256_Init, SHA256_Update, SHA256_Final,
      |                                              ^~~~~~~~~~~
In file included from /usr/include/openssl/x509.h:41,
                 from /usr/include/openssl/ssl.h:31,
                 from /duckdb/extension/httpfs/../../third_party/httplib/httplib.hpp:244,
                 from /duckdb/extension/httpfs/s3fs.cpp:12:
/usr/include/openssl/sha.h:73:27: note: declared here
   73 | OSSL_DEPRECATEDIN_3_0 int SHA256_Init(SHA256_CTX *c);
      |                           ^~~~~~~~~~~
In file included from /duckdb/extension/httpfs/s3fs.cpp:12:
/duckdb/extension/httpfs/../../third_party/httplib/httplib.hpp:4189:59: warning: 'int SHA256_Update(SHA256_CTX*, const void*, size_t)' is deprecated: Since OpenSSL 3.0 [-Wdeprecated-declarations]
 4189 |         return message_digest<SHA256_CTX>(s, SHA256_Init, SHA256_Update, SHA256_Final,
      |                                                           ^~~~~~~~~~~~~
In file included from /usr/include/openssl/x509.h:41,
                 from /usr/include/openssl/ssl.h:31,
                 from /duckdb/extension/httpfs/../../third_party/httplib/httplib.hpp:244,
                 from /duckdb/extension/httpfs/s3fs.cpp:12:
/usr/include/openssl/sha.h:74:27: note: declared here
   74 | OSSL_DEPRECATEDIN_3_0 int SHA256_Update(SHA256_CTX *c,
      |                           ^~~~~~~~~~~~~
In file included from /duckdb/extension/httpfs/s3fs.cpp:12:
/duckdb/extension/httpfs/../../third_party/httplib/httplib.hpp:4189:74: warning: 'int SHA256_Final(unsigned char*, SHA256_CTX*)' is deprecated: Since OpenSSL 3.0 [-Wdeprecated-declarations]
 4189 |         return message_digest<SHA256_CTX>(s, SHA256_Init, SHA256_Update, SHA256_Final,
      |                                                                          ^~~~~~~~~~~~
In file included from /usr/include/openssl/x509.h:41,
                 from /usr/include/openssl/ssl.h:31,
                 from /duckdb/extension/httpfs/../../third_party/httplib/httplib.hpp:244,
                 from /duckdb/extension/httpfs/s3fs.cpp:12:
/usr/include/openssl/sha.h:76:27: note: declared here
   76 | OSSL_DEPRECATEDIN_3_0 int SHA256_Final(unsigned char *md, SHA256_CTX *c);
      |                           ^~~~~~~~~~~~

### To Reproduce

1. install build dependencies
yum install build-essential cmake git openssl-devel python3-devel -y

2. install python dependencies
pip3 install setuptools numpy

3. clone repo with source code
git clone https://github.com/duckdb/duckdb && cd duckdb

4. set a flag to build package with HTTPFS
export BUILD_HTTPFS=1
make

### OS:

aws linux2

### DuckDB Version:

4

### DuckDB Client:

Python

### Full Name:

Vivek Jaganath

### Affiliation:

Sayway

### Have you tried this on the latest `master` branch?

- [X] I agree

### Have you tried the steps to reproduce? Do they include all relevant data and configuration? Does the issue you report still appear there?

- [X] I agree

**Comment by lnkuiper** [comment]
Did you install OpenSSL 3.0? I have also seen a bunch of errors for 3.0, whereas it always seems to work fine with OpenSSL 1.1

If you install 1.1, and have both 3.0 and 1.1 installed, you may need to point CMake to the correct OpenSSL using an environment variable. I have this in my `~/.zprofile` on my MacBook, but something similar should work for Linux.
```sh
export OPENSSL_ROOT_DIR="/opt/homebrew/Cellar/openssl@1.1/1.1.1q"
```

**Comment by VivekJaganath** [comment]
No luck. still the same error.

/duckdb/extension/httpfs/../../third_party/httplib/httplib.hpp:7276:21: error: 'TLS_server_method' was not declared in this scope
  ctx_ = SSL_CTX_new(TLS_server_method());
                     ^~~~~~~~~~~~~~~~~
/duckdb/extension/httpfs/../../third_party/httplib/httplib.hpp:7276:21: note: suggested alternative: 'DTLS_server_method'
  ctx_ = SSL_CTX_new(TLS_server_method());
                     ^~~~~~~~~~~~~~~~~
                     DTLS_server_method
/duckdb/extension/httpfs/../../third_party/httplib/httplib.hpp:7283:3: error: 'SSL_CTX_set_min_proto_version' was not declared in this scope
   SSL_CTX_set_min_proto_version(ctx_, TLS1_1_VERSION);
   ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/duckdb/extension/httpfs/../../third_party/httplib/httplib.hpp:7283:3: note: suggested alternative: 'SSL_CTX_set_ssl_version'
   SSL_CTX_set_min_proto_version(ctx_, TLS1_1_VERSION);
   ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~
   SSL_CTX_set_ssl_version
/duckdb/extension/httpfs/../../third_party/httplib/httplib.hpp: In constructor 'duckdb_httplib_openssl::SSLServer::SSLServer(X509*, EVP_PKEY*, X509_STORE*)':
/duckdb/extension/httpfs/../../third_party/httplib/httplib.hpp:7302:21: error: 'TLS_server_method' was not declared in this scope
  ctx_ = SSL_CTX_new(TLS_server_method());
                     ^~~~~~~~~~~~~~~~~
/duckdb/extension/httpfs/../../third_party/httplib/httplib.hpp:7302:21: note: suggested alternative: 'DTLS_server_method'
  ctx_ = SSL_CTX_new(TLS_server_method());
                     ^~~~~~~~~~~~~~~~~
                     DTLS_server_method
/duckdb/extension/httpfs/../../third_party/httplib/httplib.hpp:7309:3: error: 'SSL_CTX_set_min_proto_version' was not declared in this scope
   SSL_CTX_set_min_proto_version(ctx_, TLS1_1_VERSION);
   ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/duckdb/extension/httpfs/../../third_party/httplib/httplib.hpp:7309:3: note: suggested alternative: 'SSL_CTX_set_ssl_version'
   SSL_CTX_set_min_proto_version(ctx_, TLS1_1_VERSION);
   ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~
   SSL_CTX_set_ssl_version
/duckdb/extension/httpfs/../../third_party/httplib/httplib.hpp: In constructor 'duckdb_httplib_openssl::SSLServer::SSLServer(const std::function<bool(ssl_ctx_st&)>&)':
/duckdb/extension/httpfs/../../third_party/httplib/httplib.hpp:7326:21: error: 'TLS_method' was not declared in this scope
  ctx_ = SSL_CTX_new(TLS_method());
                     ^~~~~~~~~~
/duckdb/extension/httpfs/../../third_party/httplib/httplib.hpp:7326:21: note: suggested alternative: 'DTLS_method'
  ctx_ = SSL_CTX_new(TLS_method());
                     ^~~~~~~~~~
                     DTLS_method
/duckdb/extension/httpfs/../../third_party/httplib/httplib.hpp: In constructor 'duckdb_httplib_openssl::SSLClient::SSLClient(const string&, int, const string&, const string&)':
/duckdb/extension/httpfs/../../third_party/httplib/httplib.hpp:7386:21: error: 'TLS_client_method' was not declared in this scope
  ctx_ = SSL_CTX_new(TLS_client_method());
                     ^~~~~~~~~~~~~~~~~
/duckdb/extension/httpfs/../../third_party/httplib/httplib.hpp:7386:21: note: suggested alternative: 'DTLS_client_method'
  ctx_ = SSL_CTX_new(TLS_client_method());
                     ^~~~~~~~~~~~~~~~~
                     DTLS_client_method
/duckdb/extension/httpfs/../../third_party/httplib/httplib.hpp: In constructor 'duckdb_httplib_openssl::SSLClient::SSLClient(const string&, int, X509*, EVP_PKEY*)':
/duckdb/extension/httpfs/../../third_party/httplib/httplib.hpp:7407:21: error: 'TLS_client_method' was not declared in this scope
  ctx_ = SSL_CTX_new(TLS_client_method());
                     ^~~~~~~~~~~~~~~~~
/duckdb/extension/httpfs/../../third_party/httplib/httplib.hpp:7407:21: note: suggested alternative: 'DTLS_client_method'
  ctx_ = SSL_CTX_new(TLS_client_method());

**Comment by orzom411** [comment]
Good Morning, I had the same sort of issues with windows build.  After some scratching and searching I ended up building ssl (painful process but I was able to work that out) then it was cmake:

Windows build.

set OPENSSL_ROOT_DIR=C:\ssl\x64\lib\release
cmake -DCMAKE_BUILD_TYPE=Release -DCMAKE_EXPORT_COMPILE_COMMANDS=1 -DBUILD_PARQUET_EXTENSION=1 -DBUILD_VISUALIZER_EXTENSION=1 -DBUILD_HTTPFS_EXTENSION=1 -DBUILD_JSON_EXTENSION=1 -DBUILD_EXCEL_EXTENSION=1 -DBUILD_ODBC_DRIVER=1 .\

Then in Visual Studio I had to find references to the SSL library and set them correctly.  Here is my raw note on what I did:

Back into Visual Studio, loaded the DuckDB project, and attempted a build.  Few failures I saw wiz by, not sure but wait till it completes before ranting at the thing.  More openssl issues, can't open file openssl/err.h, part of the httpfs extension (my whole reason for going through this process).  The solution turns out within DuckDB project the include folder turned out to be one level too deep but I'm not sure how I could have corrected it using cmake syntax.   The environment var OPENSSL_ROOT_DIR got me past the more perplexing issue but what remained was a failure to find the err.h.  There are over a hundred different sub projects within the duckdb build sequence and it turned out the include folder wasn't cleanly nested for sub-projects like the httpfs, it set is as "C:\ssl\x64\lib\release\openssl" but the include syntax specifically states "openssl\include", e.g. nesting it one layer deeper, oops.  Corrective action took a bit as I'm not fully versed on how to find things in VS (the search options are limited) nor could I unearth the data point outside.  So what I did was added to any httpfs sub project the proper include folder "C:\ssl\x64\lib\release" and then compiled each individually to confirm the issue was addressed.  Took a bit as there is more than one reference and I think I found the correct one last (always the last place you look).

Sorry the note is rather raw, I rarely compile and things have changed vastly over the last thirty years... 
Hope that helps.
