### ISSUE TITLE
_SC_PHYS_PAGES problem on OSX

### ISSUE THREAD

**Issue by izahn** [duckdb/duckdb#1714]
I'm trying to build a conda-forge package for R duckdb package over at https://github.com/conda-forge/staged-recipes/pull/14813

It builds find on Linux and Windows, but on OSX I get

```
duckdb/src/common/file_system.cpp:349:52: error: use of undeclared identifier '_SC_PHYS_PAGES'
        idx_t max_memory = MinValue<idx_t>((idx_t)sysconf(_SC_PHYS_PAGES) * (idx_t)sysconf(_SC_PAGESIZE), UINTPTR_MAX);
                                                          ^
```

**Comment by hawkfish** [comment]
[This](https://stackoverflow.com/questions/30511579/linux-sc-phys-pages-not-working-on-mac-os-x) may have a solution.

**Comment by hannesmuehleisen** [comment]
Its odd since we both build on OSX 10.15 it seems.

**Comment by izahn** [comment]
Indeed `-mmacosx-version-min=10.9` was the cause, thank you!
