### PR TITLE
Fix for build error of R package on Windows

### PR DESCRIPTION
**Pull request by rsund**
It is currently impossible to build i386 (32-bit) R package on Windows using rtools40 (used with R 4.0 (oldrel) and R 4.1 (currel) but not with R 4.2 (devrel)) as building stops on two errors:
 
```
In file included from duckdb/amalgamation-1.cpp:87:
duckdb/src/common/local_file_system.cpp: In member function 'virtual bool duckdb::LocalFileSystem::FileExists(const string&)':
duckdb/src/common/local_file_system.cpp:59:17: error: cannot convert '_stat64i32*' to '_stat*'
   _wstat(wpath, &status);
```

```
In file included from duckdb/amalgamation-1.cpp:87:
duckdb/src/common/local_file_system.cpp: In member function 'virtual bool duckdb::LocalFileSystem::IsPipe(const string&)':
duckdb/src/common/local_file_system.cpp:71:17: error: cannot convert '_stat64i32*' to '_stat*'
   _wstat(wpath, &status);
```

Probably the problem was introduced in commit 664d1f25defd3392ce2deeb28f55d0d672e40c00. Unclear why this was not detected in the CI checks.

If the type `_stat64i32` is correct, this seems to be easy to fix by changing `_wstat` to `_wstat64i32`.

### CODE REVIEW

**Comment by hannes** [comment]
CC @pdet

**Comment by pdet** [comment]
I'm fine with this change. I only wonder if we should make an effort to test this specific case in our CI.

**Comment by rsund** [comment]
R 4.1 will be the last R version with 32bit support on Windows, as 4.2 (i.e. current development version) will be 64bit (and with native support for utf-8). So actually the problematic case can't be seen with R 4.2 and it would probably be good to have CI check also for R release 4.1 (and/or R oldrelease) as CRAN propably don't like failing builds on release (or oldrelease) version.

A new CI check for R release version on Windows should be straightforward to implement. Would you like to have a commit or a new PR for that?

**Comment by hannes** [comment]
@rsund re. 2, I have removed those pragmas manually last time for CRAN. Indeed we need a better solution there.
