### ISSUE TITLE
error: 'SYS_getrandom' was not declared in this scope on Ubuntu 20.04

### ISSUE THREAD

**Issue by zmbc** [duckdb/duckdb#15967]
### What happens?

DuckDB after [this commit](https://github.com/duckdb/duckdb/commit/4bc46473357403b56a48d7f21f0aeb3c8cbea190) will not compile on Ubuntu 20.04 (Linux kernel 5.4.0), with the following error:

```
In file included from ~/src/duckdb/build/debug/src/common/ub_duckdb_common.cpp:30:
~/src/duckdb/src/common/random_engine.cpp: In constructor 'duckdb::RandomEngine::RandomEngine(int64_t)':
~/src/duckdb/src/common/random_engine.cpp:24:39: error: 'SYS_getrandom' was not declared in this scope
   24 |                 auto result = syscall(SYS_getrandom, &random_seed, sizeof(random_seed), 0);
```

### To Reproduce

Attempt to compile on Ubuntu 20.04.

### OS:

Ubuntu 20.04.6 LTS (x86_64)

### DuckDB Version:

main

### DuckDB Client:

none

### Full Name:

Zeb Burke-Conte

### Affiliation:

Institute for Health Metrics and Evaluation

### What is the latest build you tested with? If possible, we recommend testing with the latest nightly build.

I have tested with a source build

### Did you include all relevant data sets for reproducing the issue?

Not applicable - the reproduction does not require a data set

### Did you include all code required to reproduce the issue?

- [x] Yes, I have

### Did you include all relevant configuration (e.g., CPU architecture, Python version, Linux distribution) to reproduce the issue?

- [x] Yes, I have

**Comment by zmbc** [comment]
It's just coming back to me that when [I had a similar issue before](https://github.com/duckdb/duckdb/discussions/11640#discussion-6497627) it was because I have my compiler installed with conda. I wonder if this is a similar issue on the conda side...

**Comment by zmbc** [comment]
I think https://github.com/conda-forge/linux-sysroot-feedstock/issues/86 is possibly the root cause, though I cannot find SYS_getrandom in BSD either: https://github.com/openbsd/src/blob/master/sys/sys/syscall.h

**Comment by szarnyasg** [comment]
Hi @zmbc thanks for reporting this. With the compiler installed from apt, it works:

```bash
$ docker run -it ubuntu:20.04 /bin/sh
```
```console
# apt update && apt install -y git g++ cmake ninja-build libssl-dev
# git clone https://github.com/duckdb/duckdb
# cd duckdb
# GEN=ninja make
```

So it may have something to do with your compiler installation.

**Comment by carlopi** [comment]
Fixed by https://github.com/duckdb/duckdb/pull/15971!
