### ISSUE TITLE
Duckdb python stubs: Wrong type hint

### ISSUE THREAD

**Issue by g-rutter** [duckdb/duckdb#12950]
### What happens?

Sorry if this the wrong place, couldn't find somewhere better.

I have this file `site-packages/duckdb-stubs/__init__.pyi` which has

`def get_table_names(self, query: str) -> List[str]: ...` (under `DuckDBPyConnection:`)

The correct hint appears to be `Set[str]`

This arose when I upgraded from 0.9.2 to 1.0.0

### To Reproduce

```python
# duckdb_test.py
import duckdb

conn = duckdb.connect()
tables: set[str] = conn.get_table_names("select 1 from my_table")
print(tables)
```

Output:
> {'my_table'}

Now run with mypy:
`mypy duckdb_test.py`

Output:
> duckdb_test.py:6: error: Incompatible types in assignment (expression has type "list[str]", variable has type "set[str]")  [assignment]
> Found 1 error in 1 file (checked 1 source file)

### OS:

Linux x64, Python 3.9, mypy 1.10.1

### DuckDB Version:

1.0.0

### DuckDB Client:

Python

### Full Name:

Gil Rutter

### Affiliation:

Maven Securities

### What is the latest build you tested with? If possible, we recommend testing with the latest nightly build.

I have tested with a stable release

### Did you include all relevant data sets for reproducing the issue?

Yes

### Did you include all code required to reproduce the issue?

- [X] Yes, I have

### Did you include all relevant configuration (e.g., CPU architecture, Python version, Linux distribution) to reproduce the issue?

- [X] Yes, I have
