### PR TITLE
feat(py): Py3.12 support for Windows

### LINKED ISSUE #9301: Error in pip install duckDB
### What happens?

Afternoon guys, 

to start, massive fan of duckDB! This stuff is transformational. 

I'm getting an error when i tried to install duckDB (pip install duckdb==0.9.0). 

I'm installing on a venv, on python 3.12.0. This is a brand new server i'm having issue with, i have no issue with other server running older version (in fact, i could actually upgrade it). 

I can't debug the error message and i'm getting below (a snapshot of a long one). 

      duckdb_build/extension/jemalloc/jemalloc/include\jemalloc/jemalloc.h(267): error C2485: '__restrict': unrecognized extended attribute
      duckdb_build/extension/jemalloc/jemalloc/include\jemalloc/jemalloc.h(269): error C2485: '__restrict': unrecognized extended attribute
      duckdb_build/extension/jemalloc/jemalloc/include\jemalloc/jemalloc.h(273): error C2485: '__restrict': unrecognized extended attribute
      duckdb_build/extension/jemalloc/jemalloc/include\jemalloc/jemalloc.h(275): error C2485: '__restrict': unrecognized extended attribute
      duckdb_build/extension/jemalloc/jemalloc/include\jemalloc/jemalloc.h(279): error C2485: '__restrict': unrecognized extended attribute
      duckdb_build/extension/jemalloc/jemalloc/include\jemalloc/jemalloc.h(281): error C2485: '__restrict': unrecognized extended attribute
      duckdb_build/extension/jemalloc/jemalloc/include\jemalloc/internal/jemalloc_internal_macros.h(36): warning C4005: 'restrict': macro redefinition
      duckdb_build/extension/jemalloc/jemalloc/include\jemalloc/internal/jemalloc_internal_decls.h(87): note: see previous definition of 'restrict'
      error: command 'C:\\Program Files (x86)\\Microsoft Visual Studio\\2022\\BuildTools\\VC\\Tools\\MSVC\\14.37.32822\\bin\\HostX86\\x64\\cl.exe' failed with exit code 2
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for duckdb
Failed to build duckdb
ERROR: Could not build wheels for duckdb, which is required to install pyproject.toml-based projects

### To Reproduce

pip install duckdb==0.9.0

### OS:

x64

### DuckDB Version:

0.9.0

### DuckDB Client:

Python

### Full Name:

Maha Kepakisan

### Affiliation:

DDB

### Have you tried this on the latest `main` branch?

I have tested with a main build

### Have you tried the steps to reproduce? Do they include all relevant data and configuration? Does the issue you report still appear there?

- [X] Yes, I have

### LINKED ISSUE #9563: Py wheel fails to build with Python 3.12.0
### What happens?

duckdb python package 0.9.1 fails to build with python 3.12.0

When I downgrade to python 3.11.0 it builds successfully. 

In python 3.12.0,  `Legacy Unicode APIs based on Py_UNICODE* representation has been removed. Please migrate to APIs based on UTF-8 or wchar_t*.`. (https://docs.python.org/dev/whatsnew/3.12.html). 

Error message I get: 
```
      src/numpy/numpy_scan.cpp:402:69: error: ‘PyUnicode_WCHAR_KIND’ was not declared in this scope; did you mean ‘PyUnicode_4BYTE_KIND’?
                
```

### To Reproduce

I am using conda, so the repro here is assuming you use it to isolate your dependency. 

conda create -n repro python=3.12.0
conda activate repro 
pip install duckdb --upgrade --pre

...Downloading duckdb-0.9.2.dev242.tar.gz (10.7 MB)

### OS:

Linux devvm 6.2.0-36-generic #37~22.04.1-Ubuntu SMP PREEMPT_DYNAMIC Mon Oct  9 15:34:04 UTC 2 x86_64 x86_64 x86_64 GNU/Linux

### DuckDB Version:

0.9.1

### DuckDB Client:

python

### Full Name:

Wei Xin Yuan

### Affiliation:

None 

### Have you tried this on the latest `main` branch?

I have tested with a release build (and could not test with a main build)

### Have you tried the steps to reproduce? Do they include all relevant data and configuration? Does the issue you report still appear there?

- [X] Yes, I have

### PR DESCRIPTION
**Pull request by Mause**
Linux and MacOS support was added in a previous PR.

This essentially works around an issue in the setuptools copy of distutils (as opposed to the one that was left frozen in the CPython standard library) that causes link.exe calls to fail on Windows.

The issue is that the call winds up being too long for Windows' limit, which is around 32677 characters, so we use the weird ancient "short paths" to shorten the call. There's a chance this might reoccur in the future though. If that happens, we might have to look into other build systems (instead of setuptools), such as Meson, Bazel, Pants, etc.

Fixes https://github.com/duckdb/duckdb/issues/9301
Fixes https://github.com/duckdb/duckdb/issues/9563

### CODE REVIEW

**Comment by Mytherin** [comment]
Sounds like a gnarly issue! Thanks :)

File: .github/workflows/Python.yml [hunk 1]
```diff
@@ -280,7 +280,7 @@ jobs:
       runs-on: windows-2019
       strategy:
        matrix:
-        python_build: [cp37-*, cp38-*, cp39-*, cp310-*, cp311-*] # , cp312-*] # TODO: figure out windows build issues
+        python_build: [cp37-*, cp38-*, cp39-*, cp310-*, cp311-*, cp312-*]
```
Comment (Bidek56) [inline .github/workflows/Python.yml:283]: I think you can remove `cp37` by now. :)

**Comment by Mause** [comment]
> Sounds like a gnarly issue! Thanks :)

Yup 😅 I've raised an issue against setuptools as well: https://github.com/pypa/setuptools/issues/4177
