### ISSUE TITLE
Windows CI for the Julia Pkg errors with 'Could not load symbol "duckdb_vector_size"'

### ISSUE THREAD

**Issue by abelsiqueira** [duckdb/duckdb#13911]
### What happens?

We have a failing Julia package build with DuckDB_jll 1.1.0 for Windows GitHub runners: https://github.com/TulipaEnergy/TulipaEnergyModel.jl/actions/runs/10833112611/job/30062514253

Revelant part reproduced:

```
ERROR: LoadError: could not load symbol "duckdb_vector_size":
The specified procedure could not be found. 
```

I saw other failures on 1.1.0, but I couldn't tell if they were related to this issue or not.

### To Reproduce

I created a simple repo building a Julia package that runs DuckDB here: https://github.com/abelsiqueira/DuckDBDebug.jl/actions/runs/10835456425/job/30067028887

You can see:
- It passes for ubuntu on DuckDB_jll 1.0.0 and 1.1.0
- It passes for Windows on DuckDB_jll 1.0.0
- It fails for Windows on DuckDB_jll 1.1.0

The code is very simple, and it doesn't actually run, since it fails on precompilation, but everything is included in the repo (https://github.com/abelsiqueira/DuckDBDebug.jl).

### OS:

windows-latest on CII

### DuckDB Version:

1.1.0

### DuckDB Client:

Julia

### Full Name:

Abel Soares Siqueira

### Affiliation:

Netherlands eScience Center

### What is the latest build you tested with? If possible, we recommend testing with the latest nightly build.

I have tested with a stable release

### Did you include all relevant data sets for reproducing the issue?

Yes

### Did you include all code required to reproduce the issue?

- [X] Yes, I have

### Did you include all relevant configuration (e.g., CPU architecture, Python version, Linux distribution) to reproduce the issue?

- [X] Yes, I have

**Comment by szarnyasg** [comment]
Hi @abelsiqueira and @ansaardollie, thanks for opening this issue and joining the discussion. The DuckDB Julia API is experimental and [not covered by community support](https://duckdblabs.com/news/2023/10/02/support-policy#apis). We welcome contributions fixing this issue but the core team is unlikely to fix this bug in the near future.

**Comment by abelsiqueira** [comment]
Thanks for the reply @szarnyasg. Just an update on our side, `DuckDB_jll@v1.1.0` is broken on local Windows machines as well, not just the CI.

Maybe limiting the `DuckDB` dependency on `DuckDB_jll` to `=1.0.0` is a workaround until it's fixed.

For other users, you can `add` and `pin` `DuckDB_jll` to `v1.0.0` with

```Julia-repl
pkg> add DuckDB_jll@v1.0.0
pkg> pin DuckDB_jll@v1.0.0
```

Since `DuckDB` compat bounds include `DuckDB_jll` 1.1.0, then you either do that or pin `DuckDB` itself to `v0.10.3`.

**Comment by szarnyasg** [comment]
Thanks for the additional info, this definitely warrants a look on our side.

**Comment by Mytherin** [comment]
Does this issue still persist with DuckDB 1.1, or is this issue specifically about using DuckDB 1.0 in combination with DuckDB_jll 1.1?

**Comment by abelsiqueira** [comment]
It was about DuckDB.jl 1.0 with jll 1.1, because DuckDB.jl 1.1.0 was not around yet. But I reran the tests in https://github.com/abelsiqueira/DuckDBDebug.jl/actions/runs/10835456425/job/30067028887 and they also fail with DuckDB.jl 1.1.0

**Comment by abelsiqueira** [comment]
I'm on the phone hope this is the link: https://github.com/abelsiqueira/DuckDBDebug.jl/actions/runs/10835456425/job/30358662742#step:8:221

**Comment by jhmenke** [comment]
I can confirm this issue on a number of different Windows 10 computers.

I guess the Windows libduckdb is not compiled correctly. A temporary fix was:

[compat]
DuckDB_jll = "=1.0.0"

in the Project.toml

**Comment by abelsiqueira** [comment]
Maybe version 1.1.1 fixes the issue? Can we have new DuckDB_jll and DuckDB.jl releases?

**Comment by mzy2240** [comment]
Still an issue in Windows

**Comment by GhostOfElectric** [comment]
If the 1.1.1 C/C++ windows library is downloaded from the website and an environment variable  JULIA_DUCKDB_LIBRARY is set to point at duckdb.dll within it, then the latest version will successfully compile in Julia on windows.

**Comment by jdpavek** [comment]
Thanks, GhostOfElectric.  that worked for me.

**Comment by KronosTheLate** [comment]
> If the 1.1.1 C/C++ windows library is downloaded from the DuckDB website and an environment variable JULIA_DUCKDB_LIBRARY is set to point at duckdb.dll within it, then the latest version will successfully compile in Julia on windows.

If version 1.1.1 of the binary works with DuckDB.jl, then I figures that the fix would be updating the binary. I triggered that in [this PR](https://github.com/JuliaPackaging/Yggdrasil/pull/9731), which might just fix this issue on your next update.

For future reference, I am pretty sure that one could automate a github workflow to trigger on a new tag, and create a PR with the tiny changes required to trigger a new build. This would ensure that the binary stays updated.

**Comment by KronosTheLate** [comment]
The outline for a workflow `.github/workflows/JuliaRelease.yml` could be something like this:

```
name: On Tag

on:
  push:
    tags:        
      - 'v[0-9]+.[0-9]+.[0-9]+'

env:
  branch_name: update_duckdb_jll
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

permissions:
  id-token: write
  contents: read

jobs:
  update_duckdb:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Clone Yggdrasil
        run: git clone https://github.com/JuliaPackaging/Yggdrasil
    
      - name: Create branch
        run: git switch -c ${{ env.branch_name }}

      - name: Update version
        run: |
          COMMIT_HASH=$(git rev-parse HEAD)
          sed -i "s|<old_commit_hash>|$COMMIT_HASH|g" path_to_file/database.jl

      - name: Commit changes
        run: |
          git add .
          git commit -m "Update DuckDB to commit $COMMIT_HASH"

      - name: Push changes
        run: git push --set-upstream origin ${{ env.branch_name }}

      - name: Create pull request
        run: gh pr create -B base_branch -H ${{ env.branch_name }} --title 'Merge ${{ env.branch_name }} into base_branch' --body 'Created by GitHub action'

**Comment by KronosTheLate** [comment]
The jll is now updated to 1.1.2, but I still got the same precompilation error. The fix provided by @GhostOfElectric worked. So it seems like the 1.1.2 C/C++ library downloaded from [here](https://duckdb.org/docs/installation/?version=stable&environment=cplusplus&platform=win&download_method=direct&architecture=x86_64) differs from the 1.1.2 library built by [Yggdrasil.jl](https://github.com/JuliaPackaging/Yggdrasil) which ends up [here](https://github.com/JuliaBinaryWrappers/DuckDB_jll.jl).

This might be related to how the windows build has specific requirements:
![image](https://github.com/user-attachments/assets/0a1bc8ea-c7b8-4470-99ca-1e6156285195)

**Comment by KronosTheLate** [comment]
I created [this discouse post](https://discourse.julialang.org/t/help-debugging-failing-precompilation-of-duckdb-jl-windows/122226) to get exta sets of eyes on this. I suspect the right person could fix this in a couple of minutes.

**Comment by suvayu** [comment]
I found the root cause, the Windows DLL does not export any of the C-API symbols (but the ADBC symbols are present). I shared more information in [this Julia discourse thread](https://discourse.julialang.org/t/debugging-could-not-load-symbol-from-jll-package/125340/6?u=suvayu). If someone can give me a hint where to look next, that would be great.  I want to fix the issue and submit a patch.

**Comment by suvayu** [comment]
I found the first bad commit: d1ea1538c9217fb536485f1500f04a0b55b1e584.

It's not clear to me how this would lead to failure to export the C-API symbols 😕

**Comment by Mytherin** [comment]
Wild guess - but maybe there's some limit on the number of symbols that can be exported that is being exceeded?

**Comment by suvayu** [comment]
> but maybe there's some limit on the number of symbols that can be exported

[What a guess](https://techcommunity.microsoft.com/discussions/windows10space/please-consider-to-remove-the-limit-of-65536-when-export-symbols-from-an-executa/1949555)! 🤦  I'll try to find more documentation, and see if it can be circumvented.

**Comment by suvayu** [comment]
The symbol count seems unlikely, since the release that works only had 335 symbols exported, and the bad commit adds about 10 more symbols.

**Comment by jonalm** [comment]
My understanding is that the error only shows up when using the DLL built by [BinaryBuilder.jl](https://github.com/JuliaPackaging/BinaryBuilder.jl), while it works when using the DuckDB provided binaries https://github.com/duckdb/duckdb/issues/13911#issuecomment-2411846873 (I'm not on Windows and haven't tested this).

Is the issue here that binaries built with (visual studio)[https://duckdb.org/docs/dev/building/windows.html] works, but not using the BinaryBuilder build pipeline?

**Comment by kobusherbst** [comment]
Yes, that is the case, when the environment variable "JULIA_DUCKDB_LIBRARY" is used to point to the downloaded library it builds, but not when the default .jll file is used produced by BinaryBuilder.

Regards

Kobus Herbst

________________________________

**Comment by trafficfan** [comment]
meet the same issue, hoping for help 
```
PkgPrecompileError: The following 1 direct dependency failed to precompile:

DuckDB

Failed to precompile DuckDB [d2f5444f-75bc-4fdf-ac35-56f514c445e1] to "C:\\Users\\admin\\.julia\\compiled\\v1.11\\DuckDB\\jl_1EAC.tmp".
ERROR: LoadError: could not load symbol "duckdb_vector_size":
The specified procedure could not be found.
Stacktrace:
 [1] duckdb_vector_size()
   @ DuckDB C:\Users\admin\.julia\packages\DuckDB\8Gvy6\src\api.jl:715
 [2] top-level scope
   @ C:\Users\admin\.julia\packages\DuckDB\8Gvy6\src\database.jl:100
 [3] include(mod::Module, _path::String)
   @ Base .\Base.jl:557
 [4] include(x::String)
   @ DuckDB C:\Users\admin\.julia\packages\DuckDB\8Gvy6\src\DuckDB.jl:1
 [5] top-level scope
   @ C:\Users\admin\.julia\packages\DuckDB\8Gvy6\src\DuckDB.jl:28
 [6] include
   @ .\Base.jl:557 [inlined]
 [7] include_package_for_output(pkg::Base.PkgId, input::String, depot_path::Vector{String}, dl_load_path::Vector{String}, load_path::Vector{String}, concrete_deps::Vector{Pair{Base.PkgId, UInt128}}, source::Nothing)
   @ Base .\loading.jl:2881
 [8] top-level scope
   @ stdin:6
in expression starting at C:\Users\admin\.julia\packages\DuckDB\8Gvy6\src\database.jl:100
in expression starting at C:\Users\admin\.julia\packages\DuckDB\8Gvy6\src\DuckDB.jl:1
in expression starting at stdin:
```

**Comment by KronosTheLate** [comment]
I tried editing the build instructions for windows to more closely match the official instructions, as an edge case, in [this PR](https://github.com/JuliaPackaging/Yggdrasil/pull/9775). However, I have gotten some pushback on the changes, as the Yggdrasil guys do not see why this would change anything. i guess they are right, so I am at a loss on how to fix the build.

**Comment by Mytherin** [comment]
Looking at this a bit more - the compile commands issued are as follows:

```cpp
 /usr/bin/ccache /opt/bin/x86_64-w64-mingw32-libgfortran3-cxx11/x86_64-w64-mingw32-g++ 
--sysroot=/opt/x86_64-w64-mingw32/x86_64-w64-mingw32/sys-root/ 
-DDUCKDB_BUILD_LIBRARY -DDUCKDB_EXTENSION_AUTOINSTALL_DEFAULT=1 -DDUCKDB_EXTENSION_AUTOLOAD_DEFAULT=1 
-DEXT_VERSION_CORE_FUNCTIONS=\"v1.2.0\" -DEXT_VERSION_JSON=\"v1.2.0\" -DEXT_VERSION_PARQUET=\"v1.2.0\" 
@CMakeFiles/duckdb_fsst.dir/includes_CXX.rsp -O3 -DNDEBUG -O3 -DNDEBUG   -fvisibility=hidden
 -w -std=c++11 -MD -MT third_party/fsst/CMakeFiles/duckdb_fsst.dir/libfsst.cpp.obj -MF 
CMakeFiles/duckdb_fsst.dir/libfsst.cpp.obj.d -o CMakeFiles/duckdb_fsst.dir/libfsst.cpp.obj -c 
/workspace/srcdir/duckdb/third_party/fsst/libfsst.cpp
```

I'm guessing the `-fvisibility=hidden` is causing the symbols to be hidden.
In the `duckdb.h` header we normally explicitly label them for export on Windows which should circumvent this:

```cpp
#ifndef DUCKDB_API
#ifdef _WIN32
#ifdef DUCKDB_STATIC_BUILD
#define DUCKDB_API
#else
#if defined(DUCKDB_BUILD_LIBRARY) && !defined(DUCKDB_BUILD_LOADABLE_EXTENSION)
#define DUCKDB_API __declspec(dllexport)
#else
#define DUCKDB_API __declspec(dllimport)
#endif
#endif
#else
#define DUCKDB_API
#endif
#endif
```

Looking at the above definitions - this also seems like it should reach the part where `DUCKDB_API` is defined as `__declspec(dllexport)`:

* `DUCKDB_API` is not defined
* `DUCKDB_STATIC_BUILD` is not defined
* `DUCKDB_BUILD_LIBRARY` is defined

The only unknown is whether or not `_WIN32` is defined. If it is not defined that could be the problem. If it is defined maybe the `__declspec` is not being correctly handled by MinGW.

Given that this worked in the past and we haven't changed anything on our end here in a long time - my guess is that something has changed on the Julia build side of things. Perhaps they did not include `-fvisibility=hidden` by default before. We do not change this setting in DuckDB's CMake. The easiest solution would be to revert to not including this setting in the build. Perhaps there's an option in the `BinaryBuilders` script somewhere?

**Comment by trafficfan** [comment]
The problem arises here. As an ordinary traffic data worker, I wasn't trained in computer science. I wanted to modify the compilation settings of my Windows system, but the Duckdb Julia API's user manual only told me to "pkg>add DuckDB" and wait for the installation. There doesn't seem to be any way to modify the compilation settings (or it's beyond my expertise). The R language's DuckDB package cannot be compiled with Rtools, but CRAN provides precompiled packages for the Windows system. I tried to copy the duckdb.dll over (this worked when changing the R language's built-in blas.dll to openblas.dll), but Julia seems to force the compilation of everything, making this method ineffective.  As I mentioned before, my lack of proficiency in C++ left me with no choice but to wait for a hero to solve the problem. But if it's a problem with Julia itself, who should I ask for help?

**Comment by abelsiqueira** [comment]
@trafficfan, the discussion and suggestions are about fixing the issue for the package. There are some comments in the beginning to bypass whe error using an earlier version. For instsance, you can do the following:

```julia-repl
julia> # Press the ] key to enter pkg mode
pkg> add DuckDB_jll@v1.0.0
pkg> pin DuckDB_jll@v1.0.0
pkg> # if DuckDB was already loaded, close and reopen julia
```

(from post https://github.com/duckdb/duckdb/issues/13911#issuecomment-2349252466), or, if you have a Project.toml, add something like in https://github.com/duckdb/duckdb/issues/13911#issuecomment-2363836767.
You can check one example on our repo: https://github.com/TulipaEnergy/TulipaEnergyModel.jl/blob/d7cba2aad8bbda2aa0cca0bbc36c99b36fc409ea/Project.toml#L27

**Comment by trafficfan** [comment]
> [@trafficfan](https://github.com/trafficfan), the discussion and suggestions are about fixing the issue for the package. There are some comments in the beginning to bypass whe error using an earlier version. For instsance, you can do the following:
> 
> julia> # Press the ] key to enter pkg mode
> pkg> add DuckDB_jll@v1.0.0
> pkg> pin DuckDB_jll@v1.0.0
> pkg> # if DuckDB was already loaded, close and reopen julia
> (from post [#13911 (comment)](https://github.com/duckdb/duckdb/issues/13911#issuecomment-2349252466)), or, if you have a Project.toml, add something like in [#13911 (comment)](https://github.com/duckdb/duckdb/issues/13911#issuecomment-2363836767). You can check one example on our repo: https://github.com/TulipaEnergy/TulipaEnergyModel.jl/blob/d7cba2aad8bbda2aa0cca0bbc36c99b36fc409ea/Project.toml#L27
I‘ve already did this. However, I use the latest Rdevel and the latest duckdb rpkg at my scholar proj ,for the possible compatibility issues I hope to find the latest version of the solution. I major in engineering,  many engineering software can only work on windows, that was why I'm limited. My homie tested DuckDB.jl on linux , it worked well.
Thanks for your advice :)

**Comment by suvayu** [comment]
> Given that this worked in the past and we haven't changed anything on our end here in a long time - my guess is that something has changed on the Julia build side of things. Perhaps they did not include `-fvisibility=hidden` by default before. We do not change this setting in DuckDB's CMake. The easiest solution would be to revert to not including this setting in the build. Perhaps there's an option in the `BinaryBuilders` script somewhere?

I replicated the problem outside of `BinaryBuilder` (that's how I could bisect).  This is how I built it:
```shell
cmake -B build \
      -DCMAKE_BUILD_TYPE=Release \
      -DCMAKE_TOOLCHAIN_FILE=mingw-w64-x86_64.cmake \
      -DBUILD_EXTENSIONS='autocomplete;icu;parquet;json;fts;tpcds;tpch' \
      -DENABLE_EXTENSION_AUTOLOADING=1 \
      -DENABLE_EXTENSION_AUTOINSTALL=1 \
      -DBUILD_UNITTESTS=FALSE \
      -DBUILD_SHELL=TRUE \
      -DDUCKDB_EXPLICIT_PLATFORM=x86_64-w64-mingw32-cxx11 .
cmake --build build
```

I used [this toolchain file](https://gist.github.com/peterspackman/8cf73f7f12ba270aa8192d6911972fe8/).

I also downloaded the build logs from older working `DuckDB_jll` windows [releases](https://github.com/JuliaBinaryWrappers/DuckDB_jll.jl/releases), e.g. 1.0.0+3, and it includes `-fvisibility=hidden`.  So maybe that is not the issue.

**Comment by suvayu** [comment]
I narrowed the issue down to this part of the build:
```shell
/usr/bin/cmake -E rm -f CMakeFiles/duckdb.dir/objects.a
/usr/bin/x86_64-w64-mingw32-ar qc CMakeFiles/duckdb.dir/objects.a @CMakeFiles/duckdb.dir/objects1.rsp
/usr/lib64/ccache/x86_64-w64-mingw32-g++ -O3 -DNDEBUG -O3 -DNDEBUG   -shared -o libduckdb.dll \
    -Wl,--out-implib,libduckdb.dll.a -Wl,--major-image-version,0,--minor-image-version,0 -Wl,--whole-archive \
    CMakeFiles/duckdb.dir/objects.a -Wl,--no-whole-archive @CMakeFiles/duckdb.dir/linkLibs.rsp
```

I tried to follow if the symbols exists and are export through the above steps:
```shell
# find the C-API object file
$ tr ' ' '\n' <CMakeFiles/duckdb.dir/objects1.rsp | grep capi.cpp
main/capi/CMakeFiles/duckdb_main_capi.dir/ub_duckdb_main_capi.cpp.obj
# check for symbols
$ nm -C main/capi/CMakeFiles/duckdb_main_capi.dir/ub_duckdb_main_capi.cpp.obj | grep duckdb_vector_size
0000000000004f60 T duckdb_vector_size
# check for the C-API object file in the objects archive
$ /usr/bin/x86_64-w64-mingw32-ar t CMakeFiles/duckdb.dir/objects.a | grep capi.cpp
ub_duckdb_main_capi.cpp.obj
# check for C-API symbols in the objects archive
$ nm -C CMakeFiles/duckdb.dir/objects.a | grep duckdb_vector_size
0000000000004f60 T duckdb_vector_size
# check if the C-API symbols are public
$ winedump -j export CMakeFiles/duckdb.dir/objects.a | grep duckdb_vector_size
 31a0ae4 duckdb_vector_size
# create the shared library
$ /usr/lib64/ccache/x86_64-w64-mingw32-g++ -O3 -DNDEBUG -O3 -DNDEBUG   -shared -o libduckdb.dll \
    -Wl,--out-implib,libduckdb.dll.a -Wl,--major-image-version,0,--minor-image-version,0 -Wl,--whole-archive \
    CMakeFiles/duckdb.dir/objects.a -Wl,--no-whole-archive @CMakeFiles/duckdb.dir/linkLibs.rsp
# the C-API symbols exist
$ nm -C libduckdb.dll | grep duckdb_vector_size
00000001f3d116e0 T duckdb_vector_size
# but they are not exported
$ winedump -j export libduckdb.dll | grep duckdb_vector_size # no match
```
(`winedump` is Linux equivalent to `objdump.exe` on Windows)

This is where I'm stuck at the moment.

**Comment by suvayu** [comment]
If someone can have a look at my PR, that would be great.

**Comment by Mytherin** [comment]
This should be fixed by https://github.com/duckdb/duckdb/pull/16397 which will land in `v1.2.1` - thanks @suvayu for doing the investigation and figuring out the problem here
